# Generated by Codex on 2026-08-08

from django.db import migrations, models
import django.db.models.deletion


INDIA_STATES = [
    'Andaman and Nicobar Islands',
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chandigarh',
    'Chhattisgarh',
    'Dadra and Nagar Haveli and Daman and Diu',
    'Delhi',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jammu and Kashmir',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Ladakh',
    'Lakshadweep',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Puducherry',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
]


def seed_india_states(apps, schema_editor):
    Country = apps.get_model('account', 'Country')
    State = apps.get_model('account', 'State')

    india, _ = Country.objects.get_or_create(
        code='IN',
        defaults={'name': 'India'}
    )

    for state_name in INDIA_STATES:
        State.objects.get_or_create(
            country=india,
            name=state_name
        )


def remove_india_states(apps, schema_editor):
    Country = apps.get_model('account', 'Country')
    Country.objects.filter(code='IN').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_city_user_district_user_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='account.country')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.RunPython(seed_india_states, remove_india_states),
    ]
