# Generated by Django 4.2.23 on 2025-07-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='reporter',
            field=models.CharField(default='Gargachary Times', max_length=100),
        ),
    ]
