# Generated by Django 6.0.1 on 2026-06-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_visitor_city_visitor_country_visitor_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='facebook_posted',
            field=models.BooleanField(default=False),
        ),
    ]
