# Generated by Django 5.2.15 on 2026-06-15 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('section', models.CharField(default='Main', max_length=80)),
                ('publish_date', models.DateField()),
                ('pdf', models.FileField(upload_to='editions/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('image', models.FileField(upload_to='editions/pages/')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='reader.edition')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('edition', 'number')},
            },
        ),
    ]
