# Generated by Django 6.0.1 on 2026-06-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_version', models.CharField(default='1.0.1', max_length=20)),
                ('min_supported_version', models.CharField(default='1.0.0', max_length=20)),
                ('force_update', models.BooleanField(default=False)),
                ('update_available', models.BooleanField(default=True)),
                ('play_store_url', models.URLField(default='https://play.google.com/store/apps/details?id=com.gargacharytimes.app')),
                ('title', models.CharField(default='Update Available', max_length=100)),
                ('message', models.TextField(default='Please update to continue using Gargacharya Times.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
