# Generated by Django 4.2.23 on 2025-12-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='city',
            field=models.BooleanField(default=False),
        ),
    ]
