# Generated by Django 6.0.1 on 2026-01-28 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_state_category_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.state'),
        ),
    ]
