# Generated by Codex on 2026-08-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=40, unique=True)),
                ('billing_name', models.CharField(max_length=150)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_mobile', models.CharField(blank=True, max_length=20)),
                ('billing_address', models.TextField(blank=True)),
                ('billing_city', models.CharField(blank=True, max_length=50)),
                ('billing_state', models.CharField(blank=True, max_length=50)),
                ('billing_pincode', models.CharField(blank=True, max_length=10)),
                ('billing_country', models.CharField(default='India', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='subscriptions.usersubscription')),
            ],
        ),
    ]
