# Generated by Codex on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_status',
            field=models.CharField(
                choices=[
                    ('NOT_REQUIRED', 'Not Required'),
                    ('PENDING', 'Pending'),
                    ('PROCESSING', 'Processing'),
                    ('SHIPPED', 'Shipped'),
                    ('DELIVERED', 'Delivered'),
                    ('CANCELLED', 'Cancelled'),
                ],
                default='PENDING',
                max_length=20
            ),
        ),
    ]
