# Generated by Django 6.0.1 on 2026-08-30 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_backfill_subscriber_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_notified_at',
            field=models.DateTimeField(blank=True, help_text='When payment/invoice confirmation was sent to the customer.', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When the subscribed service/access was confirmed delivered.', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='gateway_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='razorpay_receipt',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_dispute_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('EVIDENCE_REQUIRED', 'Evidence Required'), ('EVIDENCE_SUBMITTED', 'Evidence Submitted'), ('WON', 'Won'), ('LOST', 'Lost'), ('ACCEPTED', 'Accepted')], default='OPEN', max_length=30)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('response_due_at', models.DateTimeField(blank=True, null=True)),
                ('billing_proof', models.TextField(blank=True, help_text='Invoice, receipt, order confirmation or payment proof.')),
                ('proof_of_service', models.TextField(blank=True, help_text='Subscription activation, access, delivery or service proof.')),
                ('customer_communication', models.TextField(blank=True, help_text='Email, SMS, WhatsApp or support communication proof.')),
                ('access_activity_log', models.TextField(blank=True, help_text='Login/download/access logs for digital delivery.')),
                ('refund_policy_snapshot', models.TextField(blank=True, help_text='Refund/cancellation policy shown to the customer.')),
                ('explanation', models.TextField(blank=True)),
                ('evidence_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='subscriptions.usersubscription')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('event_name', models.CharField(db_index=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('processing_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='subscriptions.usersubscription')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_refund_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CREATED', 'Created'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='REQUESTED', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('customer_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='subscriptions.usersubscription')),
            ],
        ),
    ]
