# Generated by Django 4.2.23 on 2025-10-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspdf',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='news_image'),
        ),
    ]
