# Generated by Django 4.2.23 on 2025-12-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_pdf', '0002_newspdf_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspdf',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='news_pdf_image'),
        ),
    ]
