# Generated by Django 4.2.23 on 2025-12-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_pdf', '0003_alter_newspdf_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspdf',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
